config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "profile", to: "pages#profile"
  get "/users/:id", to: "application#custom", as: "user_id"
  get "dashboard", to: "pages#dashboard", as: "user_dashboard"

  get "step2/:id", to: "missions#new_part_two", as: "step_two"
  post "step2/:id", to: "missions#form_update_step_two", as: "update_step_two"

  get "step3/:id", to: "missions#new_part_three", as: "step_three"
  post "step3/:id", to: "missions#form_update_step_three", as: "update_step_three"

  get "edit2/:id", to: "missions#edit_part_two", as: "edit_two"
  get "edit3/:id", to: "missions#edit_part_three", as: "edit_three"
  get "rematch", to: "pages#rematch", as: "rematch"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :missions do
    resources :matches, only: [:create, :index]
  end
  resources :matches, only: :show
  # Defines the root path route ("/")
  get "lmatches/:id", to: "missions#lmatch", as: "match_landing"
  post "lmatches/:id", to: "missions#lmatch_dev_switcher", as: "lmatch_landing_dev_switcher"
  # root "articles#index"
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :dev
  belongs_to :mission
  has_many :devs
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @mission = Mission.find(params[:mission_id])
    @matches = @mission.matches
  end

  def show
    @match = Match.find(params[:id])
    @mission = @match.mission
    @matches = @mission.matches
    @dev = @match.dev
  end

  def new
    @mission = Mission.find(params[:mission_id])
    @match = Match.new
  end

  def create
    @mission = Mission.find(params[:mission_id])
    @match = Match.new(match_params)
    @match.user = current_user
    @match.mission = @mission
    @match.save!
  end

  private

  def match_params
    params.require(:match).permit(:comment)
  end

  def mission_params
    params.require(:mission).permit(:name, :description, :area, :location, :start_date, :end_date, :price)
  end
end

app/views/matches/partials/_dev_profile.html.erb
  <div class="dev-header">
    <div class="dev-avatar">
       <%= image_tag( @dev.photo, size: "400*400", class: "rounded-circle") %>
    <%# image %>
    </div>
    <div class="dev-infos" data-controller="upvote">
      <h1><strong><%= @dev.name %></strong></h1>
      <h4><%= @dev.diploma %></h4>
      <div class="dev-links">
        <h4><strong>Links</strong></h4>
          <div class="dev-links-icons">
              <a href= "<%= @dev.github_link %>" ><i class="fab fa-github glow fa-3x"></i></a>
              <a href= "<%= @dev.linkedin_link %>"><i class="fab fa-instagram glow fa-3x"></i></a>
              <a href= "<%= @dev.website_link %>"><i class="fab fa-facebook glow fa-3x"></i></a>
              <a href= "<%= @dev.twitter_link %>"><i class="fab fa-twitter glow fa-3x"></i></a>
              <a href= "<%= @dev.linkedin_link %>"><i class="fab fa-linkedin glow fa-3x"></i></a>
           </div>
      </div>
      <div class="dev-description">
        <h4><strong>Description</strong></h4>
        <p><%= @dev.description %></p>
      </div>
      <div class="dev-upvote-profile">
          <h2><strong data-upvote-target="targette"><%= @dev.upvote %></strong></h2>
          <li style="list-style:none" data-upvote-target="targetteur" data-action="click->upvote#click"><%= image_tag("upvote.png", class: "glow", :height =>"30", :width => "30") %> </li>
      </div>
    </div>
    <div class="dev-my-comment">
      <h4><strong>Your comment:</strong></h4>
         <p><%= @match.comment %></p>
    </div>
  </div>
  <div class="dev-missions">
    <div class="dev-missions-it">
       <h2><strong>Worked on:   </strong></h2>
      <% @dev.missions.each do |mission|%>
       <li><strong> <%=link_to mission.name, mission_path(mission)%> | </strong></li>
      <% end %>
    </div>
  </div>
  <div class="dev-body">
  <div class="background-dev-profile">
    <div class="dev-langs-container">
        <h2 class="title-center-profile-dev"><strong>Languages </strong></h2>
        <div class="dev-langs">

          <% @dev.languages.each do |l| %>
              <ul>
                <li style="list-style: none" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="<%= pluralize(l.langtype, "review") %>"><%= image_tag( l.langicon,  :height => "40", :width => "40", class: "rounded-circle") %></li>
              </ul>
            <% end %>
          </div>
      </div>
      <div class="dev-softs-container">
        <h2 class="title-center-profile-dev"><strong>Soft skills </strong></h2>
        <div class="dev-softs">
            <% @dev.soft_skills.each do |sk| %>
              <ul>
                  <li><%= sk.skill %></li>
              </ul>
            <% end %>
        </div>
     </div>
 </div>
    <%# dev language , dev skills  %>
    </div>
    <div class="dev-contact"
    data-controller="mailtoggler">
      <div class="avail-chat">
          <% if @dev.availability == true %>
            <%= image_tag("true.png",   :height => "40", :width => "40", class: "rounded-circle pin") %>
          <% else %>
            <%= image_tag("false.png",   :height => "40", :width => "40", class: "rounded-circle") %>
          <% end %>
          <h3 class="glow"><strong>Chat</strong></h3>
      </div>
   <div class="dev-mail"
   data-action="click->mailtoggler#toggle">
    <div data-mailtoggler-target="mail">
      <i class="fa fa-envelope glow fa-6x" aria-hidden="true"></i>
    </div>
    <div data-mailtoggler-target="email" class="d-none">
      <div class="dev-mail-text">
      <p><strong>Phone: <%= @dev.phone %></strong></p>
      <p><strong>Mail: <%= @dev.email %></strong></p>
      </div>
    </div>
  </div>
    <div data-controller="mailtoggler2"
        data-action="click->mailtoggler2#togglebell" >
        <div data-mailtoggler2-target="bell" class="ring-a-bell">
            <i class="fa-solid fa-bell glow fa-6x"></i>
        </div>
        <div class="ring-a-bell-text">
          <p data-mailtoggler2-target="bellname" class="d-none"><strong>Notification sent to <%="#{@dev.name}"%></strong></p>
        </div>
      </div>
    <%# dev availability = chat , bell to notify  %>
  </div>

app/views/matches/partials/_matching_dev.html.erb
<div class="dev-outer-card">
  <% @matches.each do |match| %>
    <div class="dev-inner-card">
        <div class="dev-inner-card-image">
          <%= link_to image_tag( match.dev.photo, class: "rounded-circle bubu"), match_path(match) %>
        </div>
        <div class="border-div">
          <div class="dev-inner-card-col">
              <h4>Infos:</h4>
                <div class="pad-title-content">
                  <h5><%= link_to match.dev.name, match_path(match) %></h5>
                  <p><%= match.dev.diploma %></p>
                  <p><%= match.dev.location %></p>
                </div>
           </div>
        </div>
        <div class="border-div">
          <div class="dev-inner-card-col">
            <h4>Languages:</h4>
              <div class="pad-title-content-title">
                <% match.dev.languages.first(2).each do |l| %>
                 <ul>
                  <li style="list-style: none" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="<%= pluralize(l.langtype, "review") %>"><%= image_tag( l.langicon,  :height => "40", :width => "40") %></li>
                </ul>
              <% end %>
            </div>
          </div>
        </div>
        <div class="border-div">
          <div class="dev-inner-card-col soft">
          <h4>Soft skills:</h4>
          <div class="pad-title-content">
              <% match.dev.soft_skills.first(2).each do |sk| %>
                <ul>
                  <li><%= sk.skill %></li>
                </ul>
              <% end %>
            </div>
          </div>
        </div>
        <div class="border-div">
            <div class="dev-inner-card-col">
              <div class="dev-inner-card-chat">
                  <% if match.dev.availability == true %>
                    <%= image_tag("true.png",  :height =>"20", :width => "20", class: "rounded-circle") %>
                  <% else %>
                    <%= image_tag("false.png",  :height =>"20", :width => "20", class: "rounded-circle") %>
                  <% end %>
                  <p>Chat</p>
              </div>
            </div>
            <div class="border-div-vote">
              <div class="dev-inner-card-vote">
                  <p><%= match.dev.upvote %></p>
                  <%= image_tag("upvote.png",  :height =>"20", :width => "20", :class => "glow") %>
              </div>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/matches/partials/_pending_mission.html.erb
      <div class="pending-nav" >
        <div class="pend-text">
          <h1><%= @mission.name %></h1>
        </div>
        <div class="pend-btn">
          <a class="my-button" href=""><%= link_to "Back to Match", match_landing_path(@mission) %></a>
        </div>
        <div class="pend-btn">
          <a class="my-button" href=""><%= link_to "Dashboard", user_dashboard_path(@dashboard) %></a>
        </div>
      </div>

      <div class="mission-specs">
        <div class="mission-desc">
          <h4>Description</h4>
          <p><%= @mission.description %> </p>
        </div>
        <div class="mission-datedom">
          <div class="mission-date">
            <h4>Date</h4>
            <p>from : <%= @mission.start_date %> to : <%= @mission.end_date %></p>
          </div>
          <div class="mission-dom">
            <h4>Area</h4>
            <p><%= @mission.area %></p>
          </div>
        </div>
        <div class="mission-langsoft">
          <div class="mission-lang">
            <h4>Languages</h4>

          <div class="lang-logos">
             <% @mission.languages.first(8).each do |language| %>
               <p style="list-style: none" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="<%= pluralize(language.langtype, "review") %>"><%= image_tag(language.langicon, size: "40x40")%></p>
              <% end %>
          </div>
          </div>
          <div class="mission-soft">
            <h4>Soft skills</h4>
            <div class="mission-soft-column">
              <% @mission.soft_skills.last(6).each do |soft_skill| %>
              <p><strong><%= soft_skill.skill %></strong> </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>