config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "profile", to: "pages#profile"
  get "/users/:id", to: "application#custom", as: "user_id"
  get "dashboard", to: "pages#dashboard", as: "user_dashboard"

  get "step2/:id", to: "missions#new_part_two", as: "step_two"
  post "step2/:id", to: "missions#form_update_step_two", as: "update_step_two"

  get "step3/:id", to: "missions#new_part_three", as: "step_three"
  post "step3/:id", to: "missions#form_update_step_three", as: "update_step_three"

  get "edit2/:id", to: "missions#edit_part_two", as: "edit_two"
  get "edit3/:id", to: "missions#edit_part_three", as: "edit_three"
  get "rematch", to: "pages#rematch", as: "rematch"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :missions do
    resources :matches, only: [:create, :index]
  end
  resources :matches, only: :show
  # Defines the root path route ("/")
  get "lmatches/:id", to: "missions#lmatch", as: "match_landing"
  post "lmatches/:id", to: "missions#lmatch_dev_switcher", as: "lmatch_landing_dev_switcher"
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i>Rooker Inc.</i>
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    By the <i class="fas fa-heart"></i> Rooker team at Le Wagon 2023 !
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://i.ibb.co/K04rmSh/Rooker-logo.png" %>
    <% end %>
    <div class="slogan">
    <p><strong>Better, faster, coder, finder.</strong></p>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1688974046/asyexd44xoypctux1gti.jpg", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "New mission", new_mission_path(@mission), class: "dropdown-item" %>
              <%= link_to "My profile", profile_path(@profile), class: "dropdown-item" %>
              <%= link_to "Dashboard", user_dashboard_path(@dashboard), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>