config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "profile", to: "pages#profile"
  get "/users/:id", to: "application#custom", as: "user_id"
  get "dashboard", to: "pages#dashboard", as: "user_dashboard"

  get "step2/:id", to: "missions#new_part_two", as: "step_two"
  post "step2/:id", to: "missions#form_update_step_two", as: "update_step_two"

  get "step3/:id", to: "missions#new_part_three", as: "step_three"
  post "step3/:id", to: "missions#form_update_step_three", as: "update_step_three"

  get "edit2/:id", to: "missions#edit_part_two", as: "edit_two"
  get "edit3/:id", to: "missions#edit_part_three", as: "edit_three"
  get "rematch", to: "pages#rematch", as: "rematch"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :missions do
    resources :matches, only: [:create, :index]
  end
  resources :matches, only: :show
  # Defines the root path route ("/")
  get "lmatches/:id", to: "missions#lmatch", as: "match_landing"
  post "lmatches/:id", to: "missions#lmatch_dev_switcher", as: "lmatch_landing_dev_switcher"
  # root "articles#index"
end

app/views/pages/_favorites.html.erb
<div class="fav-component">
      <ul>
        <% current_user.matches.last(3).each do |match| %>
          <li>
           <div class="fav-component-row">
            <div class="fav-component-avatar">
              <%= link_to image_tag( match.dev.photo, style: 'height:50px;width:50px;', class: "rounded-circle bubu"), match_path(match) %>
            </div>
            <div class="fav-component-infos">
               <h6><strong><%= match.dev.name %></strong></h6>
               <h6 ><%= match.dev.diploma %></h6>
               <h6><%= match.dev.location %></h6>
            </div>
              <ul>
            <div class="fav-component-languages">
                <% match.dev.languages.first(5).each do |l| %>
                  <li style="list-style:none" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="<%= pluralize(l.langtype, "review") %>"><%= image_tag(l.langicon, size: "30x30")%> </li>
                <% end %>
            </div>
              </ul>
          </div>
          </li>
        <% end %>
      </ul>
</div>

app/views/pages/_mission_history.html.erb
   <% @missions.each do |mission| %>
        <div class="history-comp">

          <div class="hist-elmnt1">
            <h4><%= link_to mission.name, mission_path(mission) %></h4>
            <p><%= mission.description %></p>
          </div>
          <div class="hist-elmnt2">
            <div class="soft-elmnt">
              <h4>Soft skills</h4>
              <% mission.soft_skills.last(3).each do |soft_skill| %>
                <p><%= soft_skill.skill %> </p>
              <% end %>
            </div>
          </div>


          <div class="hist-elmnt3">
            <div class="date-elmnt">
              <h4> Date</h4>
              <p>From <%= mission.start_date %> to <%= mission.end_date %></p>
            </div>
          </div>

          <div class="hist-elmnt4">
            <div>
              <h4>Languages</h4>
            </div>
            <div>
              <ul class="tooltip-flex">
              <% mission.languages.each do |language| %>
                  <li style="list-style:none" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="<%= pluralize(language.langtype, "review") %>"><%= image_tag(language.langicon, size: "35x35")%> </li>
               <% end %>
              </ul>
            </div>
          </div>
          <div class="hist-elmnt5">
            <div>
              <h4>Devs</h4>
            </div>
            <div class="dev-elmnt">
              <% mission.devs.each do |dev| %>
                  <% if dev.photo.present? %>
                    <%= image_tag (dev.photo), size: "40X40", class:"rounded-circle" %>
                  <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>

app/views/pages/dashboard.html.erb
<%# <div class="container"> %>
<div class="todo">
  <div class="frame">
    <div class="new-miss-frame">
      <div class="createmission">
        <div class="newmission"><%= link_to "Create a new mission", new_mission_path(@mission) %>
        </div>
      </div>
    </div>
  </div>

  <div class="frame-dos">

    <div class="missions">
      <div class="titulo-miss">
        <h2>Missions</h2>
        <span class="linea"></span>
      </div>
        <% @missions.last(3).each do |mission| %>
          <div class="namego">
            <p class="missionname"><strong><%= link_to mission.name, mission_path(mission) %></strong></p>
            <p class="go"><%= link_to "Go", mission_path(mission) %></p>
          </div>
        <% end %>
    </div>
    <div class="favoris">
      <div class="titulo-favs">
        <h2>Favorites</h2>
        <span class="linea"></span>
        </div>
        <%= render "favorites", locals: {current_user: current_user, mission: @mission} %>
    </div>

  </div>
  <div class="frame-tres">
      <div class="titulo">
        <h2> History </h2>
        <span class="linea"></span>
      </div>
    <div class="custom-container">
      <%= render "mission_history", locals: {missions: @missions} %>
    </div>
  </div>
</div>
<%# </div> %>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1593720213428-28a5b9e94613?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80);">
  <div class="container">
    <h1 class="megatitle">ROOKER, find the best rookie dev in SECONDS !</h1>
    <p>Better, Faster, Coder, Finder!</p>
    <%# <%= link_to "Let's go", user_dashboard_path, class: "btn btn-gradient" %>
  </div>
    <div class="boton">
    <%= link_to "Let's go!", user_dashboard_path, class: "lolosbtn" %>
    </div>
</div>

app/views/pages/profile.html.erb
<h1>Your profile</h1>
<p>Hello <%= current_user.email %>!</p>
<div class="big-center" style="column-count= 2">
  <div>
    <h2>Here goes your current missions</h2>
    <h2>Here goes your missions history</h2>
  </div>
  <div>
     <h2>Here goes your infos</h2>
  </div>
  <div>
     <h2>Here goes your favs</h2>
  </div>

</div>

app/views/pages/rematch.html.erb
<h1>REMATCH PAGE </h1>
<button><%= link_to "VOS PROFILS", match_path(@match) %></button>
<div><% @devs.each do |dev| %>
  <p>your dev<%= dev.name %></p>
  <button>I want you</button>
  <button>next</button>
  <p>upvote<%= dev.upvote %></p>
  <p><%= dev.email %></p>
  <p>Work area:<%= dev.area %></p>
  <p>Diploma: <%= dev.diploma%></p>
  <% end %>
</div>

<%= link_to "Retour", edit_mission_path(@mission) %>