config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "profile", to: "pages#profile"
  get "/users/:id", to: "application#custom", as: "user_id"
  get "dashboard", to: "pages#dashboard", as: "user_dashboard"

  get "step2/:id", to: "missions#new_part_two", as: "step_two"
  post "step2/:id", to: "missions#form_update_step_two", as: "update_step_two"

  get "step3/:id", to: "missions#new_part_three", as: "step_three"
  post "step3/:id", to: "missions#form_update_step_three", as: "update_step_three"

  get "edit2/:id", to: "missions#edit_part_two", as: "edit_two"
  get "edit3/:id", to: "missions#edit_part_three", as: "edit_three"
  get "rematch", to: "pages#rematch", as: "rematch"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :missions do
    resources :matches, only: [:create, :index]
  end
  resources :matches, only: :show
  # Defines the root path route ("/")
  get "lmatches/:id", to: "missions#lmatch", as: "match_landing"
  post "lmatches/:id", to: "missions#lmatch_dev_switcher", as: "lmatch_landing_dev_switcher"
  # root "articles#index"
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :user
  has_many :matches
  has_many :devs, through: :matches, source: :dev
  has_many :devlangmissions
  has_many :devsoftmissions
  has_many :langtypes
  has_many :languages, through: :devlangmissions
  has_many :soft_skills, through: :devsoftmissions
  validates :name, :area, :location, :description, presence: true
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  def index
    @missions = Mission.all
  end

  def show
    @mission = Mission.find(params[:id])
  end

  def new
    @mission = Mission.new
    # @mission_encours = Mission.find(params[:id])
    @dev = Dev.last
  end

  def create
    @mission = Mission.new(mission_params)
    @mission.user_id = current_user.id
    if @mission.save!
      redirect_to step_two_path(@mission)
    else
      render :new
    end
  end

  def new_part_two
    @mission = Mission.find(params[:id])
    @languages = Language.all
    @langs = Language.all
  end

  def form_update_step_two
    @mission = Mission.find(params[:id])
    selected_languages = params[:languages]
    selected_languages.each do |language|
      if language[1] == "1"
        Devlangmission.create(mission: @mission, language_id: language[0])
      end
    end
    if @mission.save!
      redirect_to step_three_path(@mission)
    else
      render :new_part_two
    end
  end

  def new_part_three
    @mission = Mission.find(params[:id])
    @skills = SoftSkill.all
  end

  def form_update_step_three
    @mission = Mission.find(params[:id])
    selected_skills = params[:skills]
    selected_skills.each do |skill|
      if skill[1] == "1"
        Devsoftmission.create(mission: @mission, soft_skill_id: skill[0])
      end
    end
    if @mission.save!
      redirect_to match_landing_path(@mission)
    else
      render :new_part_two
    end
  end

  def edit
    @mission = Mission.find(params[:id])
  end

  def update
    @mission = Mission.find(params[:id])
    if @mission.update!(mission_params)
     redirect_to match_landing_path
    end
  end

  def lmatch
    @matches = Match.all
    @lang = Language.all
    @mission = Mission.find(params[:id])
    @devs = Dev.all
    @dev_score = Dev.first


    @available_devs = Dev.get_bests_dev_for_mission(@mission) || Dev.all
    @best = @available_devs.first.id
    @dev = Dev.find(@best)
    @best_index = 0
  end

  def lmatch_dev_switcher
    @mission = Mission.find(params[:id])

    if params[:selected_dev_id].present?
      matching_dev = Dev.find(params[:selected_dev_id])
      Match.create!(mission: @mission, dev: matching_dev)
    end

    @dev_ids_by_score =  Dev.get_bests_dev_for_mission(@mission).map(&:id).uniq
    @staffed_dev_ids = Dev.get_staffed_devs(@mission).map(&:id).uniq
    @available_dev_ids = @dev_ids_by_score - @staffed_dev_ids

    unless @available_dev_ids.empty?
      if params[:best_index].present?
        @best_index = params[:best_index].to_i
        @best_index = @best_index += 1
      end

      if @best_index > (@available_dev_ids.size-1)
        @best_index = 0
      end

      @dev = Dev.find(@available_dev_ids[@best_index])
      respond_to do |format|
        format.text { render partial: "missions/lmatch", locals: {dev: @dev, mission: @mission}, formats: [:html] }
      end
    else
      respond_to do |format|
        format.text { render partial: "missions/no_more", locals: {dev: @dev, mission: @mission}, formats: [:html] }
      end
    end
  end

  private

  def mission_params
    params.require(:mission).permit(:name, :description, :area, :location, :start_date, :end_date, :price)
  end

  def match_params
    params.require(:match).permit(:comment)
  end
end

app/views/missions/_lmatch.html.erb
  <div data-controller="match"
   class="match-outer-card"
   data-match-dev-value="<%= @best %>"
   data-match-index-value="<%= @best_index %>"
   data-match-mission-id-value="<%= @mission.id %>">
    <div class="match-title"><h1 id="main-title"><strong>Mission: <%= @mission.name %></strong></h1>
    </div>
    <div class="basket">
    <div class="title-basket">
            <h2><strong>Your devs :</strong></h2>
        </div>
      <div class="basket-superpose">
          <% @mission.matches.each do |match| %>
            <li class="basket-li">
             <%= image_tag match.dev.photo , style: 'height:40px;width:40px;', data: { target: 'match.next' }, class: "rounded-circle" %>
             <%= match.dev.name %>
            </li>
          <% end %>
      </div>
    </div>
    <div class="big-center">
      <div class="match-dev-infos">

        <div class="dev-img"  >
          <%= image_tag @dev.photo , style: 'height:300px;width:300px;', data: { target: 'match.next' } %>
          <div  class="match-buttons" >

            <%= form_with url: lmatch_landing_dev_switcher_path(@mission.id), data: {
                match_target: "formSelect",
                action: "submit->match#selected"
              } do |f| %>
              <%= f.hidden_field :best_index, value: @best_index %>
              <%= f.hidden_field :selected_dev_id, value: @dev.id %>
              <%= f.submit "Select", :class => 'select-button' %>
            <% end %>


            <%= form_with url: lmatch_landing_dev_switcher_path(@mission.id), data: {
              match_target: "formNext",
              action: "submit->match#next"
              } do |f| %>
              <%= f.hidden_field :best_index, value: @best_index %>
              <%= f.submit "Next", :class => 'next-button' %>
            <% end %>
          </div>

        </div>
      <div  class="dev-details">
      <div >
        <p data-match-target="selection"> </p>
        <%# <% @thebest = Dev.find(@best) %>
        <h3 ><%= @dev.name %></h3>
        <h4><%= @dev.diploma %></h4>
      </div>
      <div>
        <h4><strong>Links</strong></h4>
           <div class="dev-links-icons">
              <a href= "<%= @dev.github_link %>" ><i class="fab fa-github glow fa-2x"></i></a>
              <a href= "<%= @dev.linkedin_link %>"><i class="fab fa-instagram glow fa-2x"></i></a>
              <a href= "<%= @dev.website_link %>"><i class="fab fa-facebook glow fa-2x"></i></a>
              <a href= "<%= @dev.twitter_link %>"><i class="fab fa-twitter glow fa-2x"></i></a>
              <a href= "<%= @dev.linkedin_link %>"><i class="fab fa-linkedin glow fa-2x"></i></a>
           </div>
      </div>
      <div >
        <p class="dev-description">
           <%= @dev.description %>
        </p>
      </div>
      <div class="skill-div">
        <h4><strong>Languages</strong></h4>
        <div class="tooltip-flex">
            <% @dev.languages.each do |language| %>
              <p data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="<%= pluralize(language.langtype, "review") %>"><%= image_tag(language.langicon, size: "30x30")%></p>
            <% end %>
        </div>
      </div>
      <div class="skill-div">
        <h4><strong>Soft skills</strong></h4>
        <ul>
          <% @dev.soft_skills.each do |sk| %>
            <li><%= sk.skill%></li>
          <% end %>
        </ul>
      </div>
      <div class="skill-div">
      <h4><strong>Infos</strong></h4>
        <p><strong>City:</strong> <%=@dev.location %></p>
        <p><strong>Area: </strong><%=@dev.area %></p>
        <div class="dev-upvote">
          <h4><strong><%= @dev.upvote %></strong></h4>
          <%= image_tag("upvote.png", class: "glow",  :height =>"24", :width => "24") %>
      </div>
      </div >
      <div class="button-div" >
        <%=link_to "Selected profiles", mission_matches_path(@mission), :class => 'btn btn-dark btn-lg'    %>
      </div>
      </div>
    </div>
  </div>
  <div>
  </div>
<%= link_to 'Back', user_dashboard_path, :class => 'btn btn-dark'  %>

</div>

app/views/missions/_no_more.html.erb
<div data-controller="match"
class="match-outer-card"
data-match-index-value="<%= @best_index %>"
data-match-mission-id-value="<%= @mission.id %>">
 <h1 id="main-title"><strong><%= @mission.name %></strong></h1>
 <div class="basket">
   <div class="basket-superpose">
       <h2><strong>Your list :</strong></h2>
       <% @mission.matches.each do |match| %>
         <li class="basket-li">
          <%= image_tag match.dev.photo , style: 'height:40px;width:40px;', data: { target: 'match.next' }, class: "rounded-circle" %>
          <%= match.dev.name %>
         </li>
       <% end %>
   </div>
 </div>
 <div class="big-center">
   <div class="match-dev-infos" style="min-height: 50vh; display: flex; justify-content: center; align-items: center;">
   <h1> TA TOUT PRIS TABUSE !!!! 🧮 🎟 🧑 🚡 ✈ 🇦🇫 🛬 🛫 </h1>
     <p data-match-target="selection"> </p>
   </div>
  </div>
</div>
<div class="button-div" >
  <button><%= link_to "Reselect", edit_mission_path(@mission) %></button>
  <button > <%=link_to "Selected profiles", mission_matches_path(@mission)  %></button>
</div>

</div>
<button><%= link_to "VOS PROFILS", mission_matches_path(@mission) %></button>
<div>
</div>

 <button><%= link_to 'Back', :back %></button>
</div>

app/views/missions/edit.html.erb
<h1>coucou editde mission</h1>

<%= simple_form_for @mission do |f| %>
  <%= f.input :name %>
  <%= f.input :area %>
  <%= f.input :location %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.button :submit %>
<% end %>

app/views/missions/index.html.erb
<h1>coucou LES MISSIONS</h1>
<% current_user.missions.all.each do |mission| %>
  <p>Nom de ma misison : <%= mission.name %> </p>
<% end %>

app/views/missions/lmatch.html.erb
<div>
   <%= render "lmatch", locals: {dev: @dev, mission: @mission} %>
</div>

app/views/missions/new.html.erb
<%# <h1><% @mission_encours.name %>

<%# <% current_user.missions.all.each do |mission| %>
  <%# <h1>Nom de ma misison : <%= mission.name %>
<%# <% end %>

<div class="form_container">
  <div class="mission-form">
    <div class="prog-space">
      <div class="prog-bar">
        <div class="step-circle activated">1
          <div class="circle-text left">Mission details</div>
        </div>
        <div class="step-line"></div>
        <div class="step-circle"> 2
          <div  class="circle-text center"> Languages</div>
        </div>
        <div class="step-line"></div>
        <div class="step-circle">
          3
          <div  class="circle-text right">Soft skills</div>
        </div>
      </div>
    </div>
    <div class="disclaimer">
      <h4> Please describe your Mission and needs </h4>
    </div>
    <%= simple_form_for @mission do |f| %>
      <div class="complete-form">
        <div class="form-left">
          <div class="vertical-form-left">
            <div class="form-gr-name">
              <%= f.input :name, label: false, :placeholder => "Mission name", input_html: { class: 'form-control' }%>
            </div>
            <div class="titopuente">
                <%= f.input :description, label: false, placeholder: "Describe your mission here...",  input_html: { rows:"9" } %>
            </div>
          </div>
        </div>
        <div class="form-extras">
          <div class="form-gr-area">
            <%= f.input :area, label: false, :placeholder =>"Business area", input_html: { class: 'form-control' }%>
          </div>
          <div class="form-gr-loc">
            <%= f.input :location, label: false, :placeholder =>"Location", input_html: { class: 'form-control' }%>
          </div>
          <div class="form-gr-price">
            <%= f.input :price, label: false, :placeholder =>"Price", input_html: { class: 'form-control' }%>
          </div>
          <div class="form-gr-price">
            <%= f.input :start_date, label: false,
                    :placeholder =>"Start date",
                    as: :string,
                    input_html: { data: { controller: "datepicker" } } %>
              <%= f.input :end_date, label: false,
                    :placeholder =>"End date",
                    as: :string,
                    input_html: { data: { controller: "datepicker" } } %>
          </div>
        </div>
      </div>
      <div class="form-gr-btn">
        <%= link_to "Dashboard", user_dashboard_path(@dashboard), class:"elotroboton" %>
        <%= f.submit 'Next step', class: 'elboton' %>
      </div>
      <% end %>
  </div>
</div>





<%# CODE D'AVANT %>


<%# <div class="form_container">
  <div class="mission-form">
  <h1>Step 1</h1>
    <br />
      <h2>Please describe your Mission and needs</h2>
        <%= simple_form_for @mission do |f| %>
          <%# <%= f.input :name, :placeholder => "Mission name"%>
          <%# <%= f.input :area, :placeholder =>"Business area"%>
          <%# <%= f.input :location, :placeholder =>"Location"%>
          <%# <%= f.input :price, :placeholder =>"0"%>
          <%# <%= f.input :start_date,
                  as: :string,
                  input_html: { data: { controller: "datepicker" } } %>
            <%# <%= f.input :end_date,
                  as: :string,
                  input_html: { data: { controller: "datepicker" } } %>
          <%# <%= f.input :description, :placeholder =>"Describe your mission here..."%>
          <%# <%= f.button :submit, 'Next step' %>
        <%# <% end %>
  <%# </div>
</div> %>




                <%# <h2 class="fs-title">Mission Details</h2>
                <h3 class="fs-subtitle">Please describe your Mission and Needs</h3>
                <input type="text" name="Name" />
                <input type="text" name="Area" />
                <input type="text" name="Location" />
                <input type="text" name="Description" />
                <input type="integer" name="Price" />
                 <input type="date" name="Start date"/>
                  <input type="date" name="End date"/>


                <h2 class="fs-title">Languages</h2>
                <h3 class="fs-subtitle">Choose up to 5 languages</h3>
                <input type="text" name="Language 1" placeholder="HTML"/>
                <input type="text" name="Language 2" placeholder="Ruby"/>
                <input type="text" name="Language 3" placeholder="Python"/>
                <input type="text" name="Language 4" placeholder="PHP"/>
                <input type="text" name="Language 5" placeholder="Javascript"/>
                <input type="button" name="previous" class="previous action-button-previous" value="Previous"/>
                <input type="button" name="next" class="next action-button" value="Next"/>
            </fieldset>
            <fieldset>
                <h2 class="fs-title">Soft Skills</h2>
                <h3 class="fs-subtitle">Choose up to 5 soft skills</h3>
                <input type="text" name="Soft skill 1" placeholder="Adaptability"/>
                <input type="text" name="Soft skill 2" placeholder="Strength of proposal"/>
                <input type="text" name="Soft skill 3" placeholder="Perseverance"/>
                <input type="text" name="Soft skill 4" placeholder="Communication"/>
                <input type="text" name="Soft skill 5" placeholder="Stress management"/> %>

app/views/missions/new_part_three.html.erb
<div class="form_container">
  <%# <div class="mission-form">
    <h1>Step 3</h1>
      <br />
      <h2>What Soft skills do you need ?</h2>
        <%= simple_form_for @mission do |f| %>
            <%# <%= simple_fields_for :languages do |l| %>
              <%# <% l.input :langtype, collection: SoftSkill.pluck(:skill) %>
            <%# <% end %>
            <%# <%= f.hidden_field :query, value: @best %>
            <%# <%= f.button :submit, "Match!" %>
          <%# <% end %>
  <%# </div> %>

  <div class="mission-form2">
    <div class="prog-space">
      <div class="prog-bar" data-controller="progress-bar">
        <div class="step-circle activated">1
          <div class="circle-text left">Mission details</div>
        </div>
        <div class="step-line active">
          <div class="step-line">
          <span class="progress-fill-bar active-progress"></span>
        </div>
        </div>
        <div class="step-circle activated">2
          <div  class="circle-text center"> Languages</div>
        </div>
        <div class="step-line active">
          <div class="step-line">
          <span class="progress-fill-bar"
          data-progress-bar-target='secondProgressFill'></span>
        </div>
        </div>
        <div class="step-circle"
        data-progress-bar-target="firstCircle">3
          <div  class="circle-text right">Soft skills</div>
        </div>
      </div>
    </div>

    <div class="disclaimer">
      <h4> Which kind of skills your dev needs to have?</h4>
    </div>

    <div class="check-group">
      <%# <% @skills.each do |item| %>
        <%# <div data-controller="newparttwo" data-newparttwo-target="clickable" class="check-frame" data-action="click->newparttwo#toggleActiveClass">
              <div class="clickable">
                <% if item.skill.present? %>
                  <%# <p><%= item.skill</p> %>
                <%# <% end %>
              <%# </div>
        </div>
      <% end %>

      <%= form_with class: "d-flex justify-content-end flex-wrap gap-3 ", url: update_step_three_path(@mission), method: 'POST' do |f| %>
        <% @skills.each do |item| %>
          <div data-controller="newparttwo" data-newparttwo-target="clickable" class="check-frame" data-action="click->newparttwo#toggleActiveClass">
              <%= f.check_box "skills[#{item.id}]", class: "d-none", "data-newparttwo-target": 'checkbox' %>
            <div class="clickable">
              <% if item.skill.present? %>
              <%= f.label item.skill, style: "font-size: 14px; margin-top: 10px; text-align: center;" %>
              <% end %>
            </div>
          </div>
        <% end %>
          <div class="check-buttons">
            <div class="previous-step">
              <p><%= link_to 'Previous step', edit_mission_path(@mission), class: "previous-link" %></p>
            </div>
            <%= f.submit 'Go find a match!', class: "next-link" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/missions/new_part_two.html.erb
<div class="form_container">

  <div class="mission-form2">
    <div class="prog-space">
      <div class="prog-bar" data-controller="progress-bar">
        <div class="step-circle activated">1
          <div class="circle-text left">Mission details</div>
        </div>
        <div class="step-line">
          <span class="progress-fill-bar"
          data-progress-bar-target='progressFill'></span>
        </div>
        <div class="step-circle"
        data-progress-bar-target="firstCircle"> 2
          <div  class="circle-text center"> Languages</div>
        </div>
        <div class="step-line"></div>
        <div class="step-circle">
          3
          <div  class="circle-text right">Soft skills</div>
        </div>
      </div>
    </div>

    <div class="disclaimer">
      <h4> Wich languages your dev has to know?</h4>
    </div>

    <div class="check-group">
      <%= form_with  class: "d-flex justify-content-end flex-wrap gap-3 ", url: update_step_two_path(@mission), method: 'POST' do |f| %>
        <% @languages.each do |language| %>
          <div data-controller="newparttwo" data-newparttwo-target="clickable" class="check-frame" data-action="click->newparttwo#toggleActiveClass">
            <%= f.check_box "languages[#{language.id}]", class: "d-none", "data-newparttwo-target": 'checkbox' %>
               <%# <input class= "test" type="checkbox" value="1" name="languages[#{language.id}]" id="languages[#{language.id}]> %>
            <div class="clickable">
              <% if language.langicon.present? %>
                <%= image_tag language.langicon, size: "40x40" %>
              <% end %>
              <%= f.label language.langtype, style: "font-size: 14px; margin-top: 10px;"%>
            </div>
          </div>
        <% end %>
          <div class="check-buttons">
            <div class="previous-step">
              <p><%= link_to 'Previous step', new_mission_path, class: "previous-link" %></p>
            </div>
            <%= f.submit 'Next step', class: "next-link" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/missions/show.html.erb
<div class="container">
  <div class="mission-title">
    <h1>Mission : <%= @mission.name %></h1>
  </div>
  <div class="missionshow">
    <div class="all-columns">
      <div class="columns">
        <div class="cols">
          <div class="mission-time">
            <h4>Date</h4>
            <p>from : <%= @mission.start_date %> <br> to : <%= @mission.end_date %></p>
          </div>
          <div class="mission-area">
            <h4>Business area</h4>
            <p><%= @mission.area %></p>
          </div>
        </div>
        <div class="cols2">
          <div class="mission-price">
            <h4>Price</h4>
            <p><%= @mission.price %>€ </p>
          </div>
          <div class="mission-location">
            <h4>Location</h4>
            <p><%= @mission.location %></p>
          </div>
        </div>
        <div class="cols-lang-devs">
          <div class="mission-languages">
            <h4>Languages</h4>
            <div class="lang-logos">
            <ul>
             <% @mission.languages.each do |language| %>
                <li style="list-style: none" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="<%= pluralize(language.langtype, "review") %>"><%= image_tag(language.langicon, size: "30x30")%></li>
              <% end %>
              </ul>
            </div>
          </div>
          <div class="mission-devs">
            <div class="selected-dev">
              <div class="select-dev-text">
                <h4>Selected Devs</h4>
              </div>
              <div class="dev-elmnt">
                <% @mission.devs.each do |dev| %>
                  <div class="dev-info">
                    <%= image_tag dev.photo , style: 'height:40px;width:40px;', class: "rounded-circle" %>
                    <p><%= dev.name%></p>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="mission-softskills">
        <h4>Soft skills</h4>
        <ul>
        <% @mission.soft_skills.last(2).each do |soft_skill| %>
        <li><%= soft_skill.skill %></li>
        <% end %>
        </ul>
      </div>
    </div>
    <div class="mission-description">
      <h4>Description</h4>
      <div class="ici-desc">
        <p><%= @mission.description %> </p>
      </div>
      <div class="show-buttons">
        <div class="button-show">
          <%= link_to "Back to Match", match_landing_path(@mission), class: "back-match" %>
        </div>
        <div class="button-show">
          <%= link_to "Dashboard", user_dashboard_path(@dashboard), class: "back-dash" %>
        </div>
      </div>
    </div>
  </div>

</div>